# Generated by Django 5.0.4 on 2024-05-06 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_remove_image_url_cloud_image_cloud_info"),
        ("tickets", "0002_alter_ticket_uploaded_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="ticket_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_images",
                to="tickets.ticket",
                verbose_name="ticket",
            ),
        ),
    ]
